package com.pandadocs.api.model;

import java.time.Instant;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "chat_conversations",
       uniqueConstraints = {
           @UniqueConstraint(columnNames = "session_id")
       },
       indexes = {
           @Index(name = "idx_chat_conversations_user_id", columnList = "user_id"),
           @Index(name = "idx_chat_conversations_session_id", columnList = "session_id"),
           @Index(name = "idx_chat_conversations_last_activity", columnList = "last_activity_at")
       })
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ChatConversation {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_id", nullable = false)
  private User user;

  @NotBlank
  @Size(max = 100)
  @Column(name = "session_id", nullable = false, unique = true)
  private String sessionId;

  @Size(max = 200)
  private String title; // Auto-generated by Gemini AI

  @Column(name = "message_count", nullable = false)
  @Builder.Default
  private Integer messageCount = 0;

  @Column(name = "created_at", nullable = false)
  @Builder.Default
  private Instant createdAt = Instant.now();

  @Column(name = "last_activity_at", nullable = false)
  @Builder.Default
  private Instant lastActivityAt = Instant.now();

  public ChatConversation(User user, String sessionId) {
    this.user = user;
    this.sessionId = sessionId;
    this.messageCount = 0;
    this.createdAt = Instant.now();
    this.lastActivityAt = Instant.now();
  }

  /**
   * Updates the last activity timestamp to now
   */
  public void updateActivity() {
    this.lastActivityAt = Instant.now();
  }

  /**
   * Increments the message count by 1
   */
  public void incrementMessageCount() {
    this.messageCount++;
  }
}
