package com.pandadocs.api.model.chat;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * In-memory chat session model (not persisted to database)
 * Holds the conversation state including message history
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ChatSession {
  /**
   * Unique session ID (UUID)
   */
  private String sessionId;

  /**
   * User ID who owns this session
   */
  private Long userId;

  /**
   * Conversation title (auto-generated by AI)
   */
  private String conversationTitle;

  /**
   * List of messages in this conversation
   */
  @Builder.Default
  private List<ChatMessage> messages = new ArrayList<>();

  /**
   * When this session was created
   */
  @Builder.Default
  private Instant createdAt = Instant.now();

  /**
   * Last activity timestamp (updated on each message)
   */
  @Builder.Default
  private Instant lastActivityAt = Instant.now();

  /**
   * Maximum number of messages allowed in a session
   */
  public static final int MAX_MESSAGES = 50;

  /**
   * Session timeout in minutes
   */
  public static final int SESSION_TIMEOUT_MINUTES = 30;

  /**
   * Adds a message to this session
   * @param message The message to add
   */
  public void addMessage(ChatMessage message) {
    this.messages.add(message);
    this.lastActivityAt = Instant.now();

    // Limit message history to prevent memory bloat
    if (this.messages.size() > MAX_MESSAGES) {
      // Keep only the most recent MAX_MESSAGES messages
      this.messages = new ArrayList<>(this.messages.subList(
        this.messages.size() - MAX_MESSAGES,
        this.messages.size()
      ));
    }
  }

  /**
   * Checks if this session has expired
   * @return true if session is older than SESSION_TIMEOUT_MINUTES
   */
  public boolean isExpired() {
    Instant cutoff = Instant.now().minusSeconds(SESSION_TIMEOUT_MINUTES * 60);
    return this.lastActivityAt.isBefore(cutoff);
  }

  /**
   * Gets the number of messages in this session
   * @return message count
   */
  public int getMessageCount() {
    return this.messages != null ? this.messages.size() : 0;
  }

  /**
   * Updates the last activity timestamp
   */
  public void updateActivity() {
    this.lastActivityAt = Instant.now();
  }
}
