-- Migration: Create Chat Tables
-- Date: 2025-11-02
-- Description: Create tables for AI chatbox feature with Gemini

-- =====================================================
-- Table: chat_conversations
-- Description: Stores metadata of chat conversations (not the actual messages)
-- Messages are stored in-memory and expire after 30 minutes
-- =====================================================
CREATE TABLE IF NOT EXISTS chat_conversations (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id VARCHAR(100) NOT NULL UNIQUE,
    title VARCHAR(200), -- Auto-generated conversation title
    message_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_activity_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for faster lookups
CREATE INDEX idx_chat_conversations_user_id ON chat_conversations(user_id);
CREATE INDEX idx_chat_conversations_session_id ON chat_conversations(session_id);
CREATE INDEX idx_chat_conversations_last_activity ON chat_conversations(last_activity_at);

-- =====================================================
-- Table: chat_quota
-- Description: Tracks rate limiting for users
-- Limits: 10 messages/hour, 30 messages/day per user
-- =====================================================
CREATE TABLE IF NOT EXISTS chat_quota (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    hourly_count INT NOT NULL DEFAULT 0,
    daily_count INT NOT NULL DEFAULT 0,
    last_hourly_reset TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_daily_reset TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for faster lookups
CREATE INDEX idx_chat_quota_user_id ON chat_quota(user_id);

-- =====================================================
-- Comments for documentation
-- =====================================================
COMMENT ON TABLE chat_conversations IS 'Stores metadata of AI chat conversations. Messages are in-memory only.';
COMMENT ON COLUMN chat_conversations.session_id IS 'UUID generated by frontend or backend for session tracking';
COMMENT ON COLUMN chat_conversations.title IS 'Auto-generated title by Gemini AI based on first message';
COMMENT ON COLUMN chat_conversations.message_count IS 'Total number of messages in this conversation';

COMMENT ON TABLE chat_quota IS 'Tracks rate limiting for AI chat feature to prevent abuse';
COMMENT ON COLUMN chat_quota.hourly_count IS 'Number of messages sent in the current hour (max 10)';
COMMENT ON COLUMN chat_quota.daily_count IS 'Number of messages sent in the current day (max 30)';
